users_app/urls.py
from django.urls import path
from .views import register, user_login, user_logout

app_name = "users-app"

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

users_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from users_app.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('user/', include('users_app.urls'))
]

users_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

users_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('portfolio_site','profile_pic')

users_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from .forms import UserForm, UserProfileForm
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'users_app/index.html')


def register(request):
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()
            return HttpResponseRedirect(reverse('users-app:login'))
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request,'users_app/register.html',{
        'user_form' : user_form,
        'profile_form': profile_form
    })


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                print('USER IS NOT ACTIVE')
        else:
            return HttpResponse('INVALID LOGIN CREDENTIALS')
    return render(request, 'users_app/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/users_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        {% block title %}
        {% endblock %}
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">
              <img src="{% static 'django.svg' %}" alt="django" width="30" height="24">
            </a>
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users-app:logout' %}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users-app:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users-app:login' %}">Login</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </nav>
        <div class="container">
          {% block body %}
          {% endblock %}
        </div>
    </body>
</html>

templates/users_app/index.html
{% extends 'users_app/base.html' %}

{% block title %}
    <title>Home Page</title>
{% endblock %}
{% block body %}
    {% if user.is_authenticated %}
        <h1>Welcome! {{ user.username }}</h1>
    {% else %}
        <h1>Welcome! to Home Page</h1>
    {% endif %}
{% endblock %}

templates/users_app/login.html
{% extends 'users_app/base.html' %}

{% block title %}
    <title>Login Page</title>
{% endblock %}
{% block body %}
    {% if registered %}
        <h5>Thank You!! for registering </h5>
    {% endif %} 
    <h1>Welcome! to Login Page</h1>
    <br>
    <form action="{% url 'users-app:login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username : </label>
        <input type="text" name="username">
        <br><br>
        <label for="password">Password : </label>
        <input type="password" name="password">
        <br><br>
        <input type="submit" value="Login" class="btn-primary" style="margin-left: 12%;">
    </form>
{% endblock %}

templates/users_app/register.html
{% extends 'users_app/base.html' %}

{% block title %}
    <title>Register Page</title>
{% endblock %}
{% block body %}
    <h1>Welcome! to Register Page</h1>
    <br><br>
    <h4>Fill the below registration form</h4>
    <br>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register" class="btn-primary" style="margin-left: 12%; font-size: large;">
    </form>
{% endblock %}